# Comical Tool Configuration
# This file contains the default configuration for Comical Tool

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080

# Database configuration
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  db_name: "comical_tool"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# Short URL service configuration
short_url:
  domain: "localhost:8080"
  code_length: 6
  allowed_chars: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  default_expiry_hours: 24
  analytics_retention_days: 30
