// Code generated by hertz generator.

package comical_tool

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _redirectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _urlsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createshortMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _codeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteshortMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getanalyticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getclickhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getshortMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateshortMw() []app.HandlerFunc {
	// your code...
	return nil
}
