// Code generated by hertz generator.

package short

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	short "github.com/kiritoxkiriko/comical-tool/biz/model/short"
)

// Short .
// @router /s [GET]
func Short(ctx context.Context, c *app.RequestContext) {
	var err error
	var req short.ShortReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(short.ShortResp)

	c.JSON(consts.StatusOK, resp)
}
