// Code generated by hertz generator.

package short

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shortMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getshortMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokeMw() []app.HandlerFunc {
	// your code...
	return nil
}
